feat(args) add read-only computed as key (#262)
Kong/swrv pull request #268
Opened 2022-02-26 10:08 UTC by ivos

As per https://github.com/Kong/swrv/issues/262

2022-02-26 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/swrv?pullRequest=268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/swrv?pullRequest=268) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/swrv?pullRequest=268) it.</sub>

2022-03-12 22:27 UTC, darrenjennings requested changes

2022-03-12 22:27 UTC, darrenjennings commented on src/types.ts
> +export type IKey = keyFunction | ComputedRef<keyType> | keyType
hey thanks for the PR! I had to bring `next` branch up to speed with `master` so now there is a conflict. You can remove this now since WatchSource encapsulates both refs and computed refs!

2022-03-12 22:27 UTC, darrenjennings commented on tests/use-swrv.spec.tsx
> +  })
nit: can you move this to below the test case that now exists `should allow refs (reactive / WatchSource) as key`

2022-03-13 12:31 UTC, ivos commented on src/types.ts
> +export type IKey = keyFunction | ComputedRef<keyType> | keyType
Removed.

2022-03-13 12:31 UTC, ivos commented on tests/use-swrv.spec.tsx
> +  })
Moved below.

2022-03-16 12:39 UTC, darrenjennings approved these changes

2022-03-17 17:19 UTC, merged