(fix) #88 always update error on revalidation
Kong/swrv pull request #93
Opened 2020-10-09 08:34 UTC by charshin

This PR is supposed to fix issue #88. I think we should always update the error after fetching, let me know if you think differently.

2020-10-09 17:24 UTC, darrenjennings requested changes

2020-10-09 17:24 UTC, darrenjennings commented on src/use-swrv.ts
> +      r.error = newData.error
can you write a test? Also, I think maybe we only want to reset the error if  `newData.error !== undefined && newData.data !== undefined` to keep the stale error hanging around until there is new valid data.

2020-10-12 02:09 UTC, charshin commented on src/use-swrv.ts
> +      r.error = newData.error
I don't think there is such a thing called stale data, after the fetching, either it was successful and the error needs to be reset or it failed and the error also needs to be updated with new error, that means we just simply reassign it to `newData.error` after every fetching. Btw, your condition `newData.error !== undefined && newData.data !== undefined` won't be true at all, they are mutually exclusive

2020-10-12 03:54 UTC, darrenjennings commented on src/use-swrv.ts
> +      r.error = newData.error
Yea that makes sense to me! Agree with the logic. Let's get a test before we merge.

2020-10-12 05:14 UTC, charshin commented on src/use-swrv.ts
> +      r.error = newData.error
Cool, thanks, test added!

2020-10-12 13:23 UTC, darrenjennings approved these changes

2020-10-12 13:25 UTC, merged